library(ddiv)
data("IV_step1")
data("IV_step2")
data("IV_step3")
data("IV_4K")
data("IV_5M_1")
data("IV_daystar")
data("IV_5M_2")
IV1 <- data.frame(IV_step1)
IV2 <- data.frame(IV_step2)
IV3 <- data.frame(IV_step3)
IVds <-data.frame(IV_daystar)
IV4k <-data.frame(IV_4K)
IV5m1 <-data.frame(IV_5M_1)
IV5m2 <-data.frame(IV_5M_2)
write.csv(IV1, 'IV1.csv')
write.csv(IV2, 'IV2.csv')
write.csv(IV3, 'IV3.csv')
write.csv(IVds, 'IVds.csv')
write.csv(IV4k, 'IV4k.csv')
write.csv(IV5m1, 'IV5m1.csv')
write.csv(IV5m2, 'IV5m2.csv')
# IVExtracResult : This function carries out IV feature extraction, by calculating steps then extract features for each step.
# IVExtractResult(dat, k = 7, crt = 0.2, num = 75, crtvalb = 0.3, plot.option = F)
#result1 <- IVExtractResult(IV3, plot.option = TRUE)
#result1_step <- IVsteps(IV3$I, IV3$V, plot.option = TRUE)
par(mfrow=c(2,2))
x <- IV3$V
y <- IV3$I
plot(x,y)
new <- smooth.spline(x,y,nknots = 41) #, all.knots = TRUE)
xnew <- seq(from = 0, to = 37, by = 0.01)
pred <- stats:::predict.smooth.spline(new, xnew)$y
lines(xnew, pred, lwd = 2, col = 2)